name: Build and Deploy NodeJS App on AWS
on:
  push:
    branches:
    - main
  
jobs:
  Build-App:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4    

      - name: Build the Docker Image
        run: |
         docker build . --tag 559050236729.dkr.ecr.us-east-1.amazonaws.com/dev/nodeimages:latest
         
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 

      - name: Login to Amazon Elastic Container Registry
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Push the Image to AWS ECR
        run: |
            docker push 559050236729.dkr.ecr.us-east-1.amazonaws.com/dev/nodeimages:latest

      - name: Revisions on ECS with Updated Docker Images
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ecs-task.json
          service: devopsmolvi-ecs-srv
          cluster: devopsmolvi-ecs
          container-name: devopsmolvi-ecs
          wait-for-service-stability: true        
